FT.manifest({
    "filename": "index.html",
    "width": 320,
    "height": 50,
    "clickTagCount": 2,
    "richLoads": [
        { "name": "main_richload", "src": "main_RL_320x50" }
    ],
    "instantAds": [
        { "name": "main_richload", "type": "richload", "default": "main_RL_320x50" },
        { "name": "CSS_text", "type": "text", "default": "" },
        { "name": "impression_URL1", "type": "text", "default": "" },
        { "name": "impression_URL2", "type": "text", "default": "" },
        { "name": "impression_URL3", "type": "text", "default": "" },
        { "name": "clicktag1_URL", "type": "text", "default": "" },
        { "name": "clicktag2_URL", "type": "text", "default": "" },
        { "name": "background_color", "type": "text", "default": "#000" },
        { "name": "background_img", "type": "image", "default": "images/Frame1_hero_320x50.jpg" },
        { "name": "logo_img", "type": "image", "default": "images/NSB_logo_320x50.png" },
        { "name": "f1_hero_img", "type": "image", "default": "images/Frame1_hero_320x50.jpg" },
        { "name": "f1_headline_txt", "type": "text", "default": "A COLLECTION OF<br>TOP CASINO GAMES" },
        { "name": "f1_headline_txt_color_size_xy", "type": "text", "default": "#fff|10|10,10" },
        { "name": "f1_subheadline_txt", "type": "text", "default": "" },
        { "name": "f1_subheadline_txt_color_size_xy", "type": "text", "default": "#fff|12|20,56" },
        { "name": "f2_hero_img", "type": "image", "default": "images/Frame2_hero_320x50.jpg" },
        { "name": "f2_headline_txt", "type": "text", "default": "ON A PLATFORM<br>YOU CAN TRUST" },
        { "name": "f2_headline_txt_color_size_xy", "type": "text", "default": "#fff|10|10,10" },
        { "name": "f2_subheadline_txt", "type": "text", "default": "" },
        { "name": "f2_subheadline_txt_color_size_xy", "type": "text", "default": "#fff|12|20,56" },
        { "name": "f3_hero_img", "type": "image", "default": "images/Frame3_hero_320x50.jpg" },
        { "name": "f3_headline_txt", "type": "text", "default": "ALL THE TOP GAMES<br>YOU LOVE TO PLAY?<br><span style='color:#5DCB78; display: inline-block;'>THAT'S A WIN</span>" },
        { "name": "f3_headline_txt_color_size_xy", "type": "text", "default": "#fff|10|10,4" },
        { "name": "f3_subheadline_txt", "type": "text", "default": "" },
        { "name": "f3_subheadline_txt_color_size_xy", "type": "text", "default": "#fff|12|20,56" },
        { "name": "f4_hero_img", "type": "image", "default": "images/Frame1_hero_320x50.jpg" },
        { "name": "f4_headline_txt", "type": "text", "default": "" },
        { "name": "f4_headline_txt_color_size_xy", "type": "text", "default": "#fff|10|10,12" },
        { "name": "f4_subheadline_txt", "type": "text", "default": "" },
        { "name": "f4_subheadline_txt_color_size_xy", "type": "text", "default": "#fff|12|20,56" },
        { "name": "f4_disclaimer_txt", "type": "text", "default": "" },
        { "name": "f4_disclaimer_txt_color_size_xy", "type": "text", "default": "#fff|10|15,75" },
        { "name": "footnote_txt", "type": "text", "default": "" },
        { "name": "footnote_txt_color_size_xy", "type": "text", "default": "#fff|2|0,0" },
        { "name": "CTA_text", "type": "text", "default": "PLAY NOW" },
        { "name": "CTA_text_color_size_xy", "type": "text", "default": "#06321b|8|233,25" },
        { "name": "CTA_background_image", "type": "image", "default": "images/CTA_background_320x50.png" },
        { "name": "CTA_text_bgColor", "type": "text", "default": "#0000" }
    ],
    "trackingEvents": []
});