FT.manifest({
    "filename": "index.html",
    "width": 728,
    "height": 90,
    "clickTagCount": 2,
    "richLoads": [
        { "name": "main_richload", "src": "main_RL_728x90" }
    ],
    "instantAds": [
        { "name": "main_richload", "type": "richload", "default": "main_RL_728x90" },
        { "name": "CSS_text", "type": "text", "default": "" },
        { "name": "clicktag1_URL", "type": "text", "default": "" },
        { "name": "clicktag2_URL", "type": "text", "default": "" },
        { "name": "background_color", "type": "text", "default": "#000" },
        { "name": "background_img", "type": "image", "default": "images/Frame1_hero_728x90.jpg" },
        { "name": "logo_img", "type": "image", "default": "images/NSB_logo_728x90.png" },
        { "name": "f1_hero_img", "type": "image", "default": "images/Frame1_hero_728x90.jpg" },
        { "name": "f1_headline_txt", "type": "text", "default": "A COLLECTION OF TOP CASINO GAMES" },
        { "name": "f1_headline_txt_color_size_xy", "type": "text", "default": "#fff|16|25,35" },
        { "name": "f1_subheadline_txt", "type": "text", "default": "" },
        { "name": "f1_subheadline_txt_color_size_xy", "type": "text", "default": "#fff|12|20,56" },
        { "name": "f2_hero_img", "type": "image", "default": "images/Frame1_hero_728x90.jpg" },
        { "name": "f2_headline_txt", "type": "text", "default": "ON A PLATFORM YOU CAN TRUST" },
        { "name": "f2_headline_txt_color_size_xy", "type": "text", "default": "#fff|16|42,32" },
        { "name": "f2_subheadline_txt", "type": "text", "default": "" },
        { "name": "f2_subheadline_txt_color_size_xy", "type": "text", "default": "#fff|12|20,56" },
        { "name": "f3_hero_img", "type": "image", "default": "images/Frame1_hero_728x90.jpg" },
        { "name": "f3_headline_txt", "type": "text", "default": "ALL THE TOP GAMES YOU LOVE TO PLAY?<br><span style='color:#5DCB78; margin-top: 4px;display: inline-block;'>THAT'S A WIN</span>" },
        { "name": "f3_headline_txt_color_size_xy", "type": "text", "default": "#fff|16|20,24" },
        { "name": "f3_subheadline_txt", "type": "text", "default": "" },
        { "name": "f3_subheadline_txt_color_size_xy", "type": "text", "default": "#fff|12|20,56" },
        { "name": "f4_hero_img", "type": "image", "default": "images/Frame1_hero_728x90.jpg" },
        { "name": "f4_headline_txt", "type": "text", "default": "" },
        { "name": "f4_headline_txt_color_size_xy", "type": "text", "default": "#fff|16|20,24" },
        { "name": "f4_subheadline_txt", "type": "text", "default": "" },
        { "name": "f4_subheadline_txt_color_size_xy", "type": "text", "default": "#fff|12|20,56" },
        { "name": "f4_disclaimer_txt", "type": "text", "default": "" },
        { "name": "f4_disclaimer_txt_color_size_xy", "type": "text", "default": "#fff|10|15,75" },
        { "name": "footnote_txt", "type": "text", "default": "" },
        { "name": "footnote_txt_color_size_xy", "type": "text", "default": "#fff|12|20,56" },
        { "name": "CTA_text", "type": "text", "default": "PLAY NOW" },
        { "name": "CTA_text_color_size_xy", "type": "text", "default": "#06321b|12|595,48" },
        { "name": "CTA_background_image", "type": "image", "default": "images/CTA_background_728x90.png" },
        { "name": "CTA_text_bgColor", "type": "text", "default": "#0000" }
    ],
    "trackingEvents": []
});