FT.manifest({
    "filename": "index.html",
    "width": 300,
    "height": 250,
    "clickTagCount": 2,
    "richLoads": [
        { "name": "main_richload", "src": "main_RL_300x250" }
    ],
    "instantAds": [
        { "name": "main_richload",                      "type": "richload", "default": "main_RL_300x250" },
        { "name": "CSS_text",                           "type": "text",     "default": "" },
        { "name": "clicktag1_URL",                      "type": "text",     "default": "" },
        { "name": "clicktag2_URL",                      "type": "text",     "default": "" },
        { "name": "background_color",                   "type": "text",     "default": "#000" },
        { "name": "background_img",                     "type": "image",    "default": "images/bg.jpg" },
        { "name": "logo_img",                           "type": "image",    "default": "images/logo.png" },
        { "name": "f1_hero_img",                        "type": "image",    "default": "images/bg.jpg" },
        { "name": "f1_headline_txt",                    "type": "text",     "default": "MVP<br>SPORTSBOOK<br>WITH BETTING<br>INSIGHTS" },
        { "name": "f1_headline_txt_color_size_xy",      "type": "text",     "default": "#fff|16|15,80" },
        { "name": "f1_subheadline_txt",                 "type": "text",     "default": "" },
        { "name": "f1_subheadline_txt_color_size_xy",   "type": "text",     "default": "#fff|12|15,80" },
        { "name": "f2_hero_img",                        "type": "image",    "default": "images/bg.jpg" },
        { "name": "f2_headline_txt",                    "type": "text",     "default": "VIP CASINO<br>GAMES<br>YOU LOVE<br>TO PLAY" },
        { "name": "f2_headline_txt_color_size_xy",      "type": "text",     "default": "#fff|16|15,80" },
        { "name": "f2_subheadline_txt",                 "type": "text",     "default": "" },
        { "name": "f2_subheadline_txt_color_size_xy",   "type": "text",     "default": "#fff|12|15,80" },
        { "name": "f3_hero_img",                        "type": "image",    "default": "images/bg.jpg" },
        { "name": "f3_headline_txt",                    "type": "text",     "default": "EXCLUSIVE<br>OFFERS JUST<br>FOR YOU"},
        { "name": "f3_headline_txt_color_size_xy",      "type": "text",     "default": "#fff|16|15,80"},
        { "name": "f3_subheadline_txt",                 "type": "text",     "default": ""},
        { "name": "f3_subheadline_txt_color_size_xy",   "type": "text",     "default": "#fff|12|15,80" },
        { "name": "f4_hero_img",                        "type": "image",    "default": "images/bg.jpg" },
        { "name": "f4_headline_txt",                    "type": "text",     "default": "CLAIM YOUR<br>EXCLUSIVE<br>OFFERS NOW<br><span style='color:#5DCB78'>THAT'S A WIN</span>" },
        { "name": "f4_headline_txt_color_size_xy",      "type": "text",     "default": "#fff|16|15,80" },
        { "name": "f4_subheadline_txt",                 "type": "text",     "default": "" },
        { "name": "f4_subheadline_txt_color_size_xy",   "type": "text",     "default": "#fff|12|15,80" },
        { "name": "f4_disclaimer_txt",                  "type": "text",     "default": "" },
        { "name": "f4_disclaimer_txt_color_size_xy",    "type": "text",     "default": "#fff|10|15,80" },
        { "name": "footnote_txt",                       "type": "text",     "default": "" },
        { "name": "footnote_txt_color_size_xy",         "type": "text",     "default": "#fff|16|15,80" },
        { "name": "CTA_text",                           "type": "text",     "default": "GET OFFER" },
        { "name": "CTA_text_color_size_xy",             "type": "text",     "default": "#fff|16|0,172" },
        { "name": "CTA_background_image",               "type": "image",    "default": "images/ctaBG.png" },
        { "name": "CTA_text_bgColor",                   "type": "text",     "default": "#0000" }
        ],
    "trackingEvents": []
});